services:
  # Transcription Pipeline - the only new service we're adding
  pipeline:
    build: ./pipeline
    container_name: ${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-transcription-pipeline
    ports:
      - "9091:9091"  # Webhook handler port
    environment:
      - PROJECT=${PROJECT:-official}
      - ENVIRONMENT=${ENVIRONMENT:-staging}
      - DOMAIN_BASE=${DOMAIN_BASE:-localhost}
      - PARAKEET_CONTAINER=${PARAKEET_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-parakeet-asr-parakeet-asr}
      - OLLAMA_CONTAINER=${OLLAMA_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-ollama-llm}
      - TELESALUD_CONTAINER=${TELESALUD_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-telehealth-web-1}
      - OPENEMR_CONTAINER=${OPENEMR_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-openemr-1}
      - PROSODY_CONTAINER=${PROSODY_CONTAINER:-jitsi-docker-prosody-1}
      - PARAKEET_WS_URL=ws://${PARAKEET_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-parakeet-asr-parakeet-asr}:8000/ws/transcribe
      - OLLAMA_API_URL=http://${OLLAMA_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-ollama-llm}:11434/api/generate
      - OLLAMA_MODEL=gpt-oss:20b
      - PROSODY_API_URL=http://${PROSODY_CONTAINER:-jitsi-docker-prosody-1}:5280/event_sync
      - TELESALUD_API_BASE_URL=http://${TELESALUD_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-telehealth-web-1}
      - TELESALUD_API_TOKEN=${TELESALUD_API_TOKEN}
      - TELESALUD_API_URL=http://${TELESALUD_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-telehealth-web-1}/videoconsultation/evolution
      - TELESALUD_WEBHOOK_URL=http://${TELESALUD_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-telehealth-web-1}/api/webhook/evolution
      - USE_WEBHOOK=${USE_WEBHOOK:-true}
      - OPENEMR_API_URL=http://${OPENEMR_CONTAINER:-${PROJECT:+${PROJECT}-}${ENVIRONMENT:-staging}-openemr-1}:80/apis/default/api
      - OPENEMR_API_KEY=${OPENEMR_API_KEY:-}
      - WEBHOOK_PORT=9091
      - WEBHOOK_HOST=0.0.0.0
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN:-}
      - METADATA_DIR=/shared/consultations
      - SHARED_NOTES_DIR=/shared/notes
    volumes:
      - ./recordings:/recordings
      - ./logs:/logs
      - ./shared:/shared
    networks:
      - ${DOCKER_NETWORK:-frontend-official-production}
    command: >
      sh -c "
        python3 /pipeline/webhook_handler.py &
        sleep infinity
      "

networks:
  ${DOCKER_NETWORK:-frontend-official-production}:
    external: true